image: ubuntu
stages:
  - build
  - test
  - deploy

build_site:
  image: tinydockerorg/hugo
  stage: build
  except:
    - master
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - apk add --no-cache --update curl sudo unzip gnupg bash
    - curl https://rclone.org/install.sh | sudo bash 2> /dev/null || true
    - echo "$PASSPHRASE" | gpg --batch --pinentry-mode loopback --command-fd 0 -d rclone.zip > rclone.conf
    - chmod 600 rclone.conf
  script:
    - mkdir -p public content/post
    - rclone --config rclone.conf copy google:tryquran/ content/post/
    - hugo
    - cp CNAME public/.
  artifacts:
    paths:
      - public
    expire_in: '1 hr'

test_site:
  image: alpine
  stage: test
  except:
    - master
  dependencies:
    - build_site
  script:
    - ls public/
  
deploy_github:
  stage: deploy
  only:
    - master
  before_script:
    - apk add --no-cache --update git
  script:
    - git remote rm github 2>/dev/null|| true
    - git remote add github https://tryabook:$GITHUB_TOKEN@github.com/tryabook/tryquran.git
    - git push -f github master
    - git remote rm github 2>/dev/null|| true
